####################
# /date_state/list #
####################
/date_state/list:
  get:
    tags:
      - DateStateRoutes
    summary: Returns a list of with all date states.
    description: Returns a list of with all date states.
    responses:
      200:
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  description: True
                data:
                  type: array
                  items:
                    $ref: ../components/schemas/DateState.yaml
      400:
        description: Bad request.
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: Error.

###################
# /date_state/:id #
###################
/date_state/{id}:
  get:
    tags:
      - DateStateRoutes
    summary: Returns the date state with this id.
    parameters:
      - name: id
        in: path
        description: DateState id
        required: true
        schema:
          type: integer
    responses:
      200:
        description: Successful operation
        content:
          application/json:
            schema:
              $ref: ../components/schemas/DateState.yaml
      400:
        description: Bad request.
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: Error.
  
  delete:
    tags:
      - DateStateRoutes
    summary: Delete the date state with this ID.
    parameters:
      - name: id
        in: path
        description: DateState id
        required: true
        schema:
          type: integer
    responses:
      200:
        description: Successful operation
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  description: True
                message:
                  type: string
                  description: Successfully deleted.
      400:
        description: Bad request.
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: Error.

###############
# /date_state #
###############
/date_state:
  post:
    tags:
      - DateStateRoutes
    summary: Add a date state to DateState table.
    parameters:
      - name: name
        in: params
        required: True
        description: DateState name
        schema:
          type: string
    responses:
      200:
        description: Successful operation
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  description: Correct.
                message:
                  type: string
                  description: Status.
                id:
                  type: integer
                  description: Date state id.
      400:
        description: Bad request.
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: Error.

  put:
    tags:
      - DateStateRoutes
    summary: Update a date state usign its id.
    parameters:
      - name: id
        in: params
        description: DateState id
        required: true
        schema:
          type: string
      - name: name
        in: params
        required: True
        description: DateState name
        schema:
          type: string
    responses:
      200:
        description: Successful operation
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  description: True
                message:
                  type: string
                  description: Successfully updated.
      400:
        description: Bad request.
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: Error.